services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: no
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
